Multiple features & fixes
pomo-mondreganto/neo pull request #10
Opened 2020-12-31 09:57 UTC by pomo-mondreganto

- [x] Cleaner releases
- [x] Github CI
- [ ] Fix [tests](https://github.com/jnovikov/neo/runs/1629774488?check_suite_focus=true)
- [ ] Fix a race in flag submission (#6)
- [ ] Run exploits ASAP (w/o waiting for the first tick)
- [ ] Run a command on all clients (e.g. install a missing requirement)
- [ ] Option to run exploit once (#9)
- [ ] Support for per-splits timeouts & "endless" sploits (#8)

2021-05-26 11:54 UTC, jnovikov requested changes
В целом конечно Good, скажу честно, прочитать досконально все сложновато, оч большой PR, но кажется удалось найти пару багосов + вопросов. 

Я постараюсь найти потом еще багосы.

2021-05-26 11:54 UTC, jnovikov commented on internal/exploit/runner.go
> +	state, err := r.pingHeartbeat(ctx)
А может если не получилось сделать первый же heartbeet не писать таки гритинг ?

2021-05-26 11:54 UTC, jnovikov commented on internal/exploit/runner.go
> +	simpleLoop := newSubmitLoop(r.maxJobs, r.cfg, queue.NewSimpleQueue)
Вот тут не очень понятно зачем нужно два сабмит лупа. 

Разве нельзя в newSubmitLoop просто передать вариадиком ...queue.Factory и делать один сабмит ?

2021-05-26 11:54 UTC, jnovikov commented on internal/exploit/runner.go
> +func (r *Runner) submitEndlessExploits(l *submitLoop) {
Мне кажется я не очень правильно понимаю submit в данном случае это же запуск нового таска ?

Просто из-за того, что есть submitLoop и submitExploit немного путаница.

2021-05-26 11:54 UTC, jnovikov commented on internal/exploit/runner.go
> +		case <-r.endlessRestarts:
Вот тут немного получается спагетти код, потому что в канал пишется неявно из другой функции.

Я бы подумал, как прямо тут в случае обновления писать в канал что нужен рестарт.

2021-05-26 11:54 UTC, jnovikov commented on internal/exploit/runner.go
>  func (r *Runner) updateExploits(ctx context.Context, exs []*neopb.ExploitState) {
Мне кажется можно смело вернуть bool или даже struct {
bool needEndlessUpdate 
}, чтобы функция "не перезапускала эксплойты" сама, а действительно только обновляла кэш эксплойтов. 

А то немного нарушается идея SOLID.

2021-05-26 11:54 UTC, jnovikov commented on internal/exploit/runner.go
> +			r.submitEndlessExploits(endlessLoop)
А мы не можем точечно перезапускать endless-сплойты ?

Я тут вижу две ситуации:

1) Поменялось распределение команд. Тут мы уповаем на силу хэширования, сохранение стэйта через редис и прочую муть и тупо перезапускаем эксплойты. 

2) Поменялась версия эксплойта / добавился новый. А давай перезапустим только те эксплойты, которые поменялись ? Мне кажется или это сейчас не так ?

2021-06-02 22:33 UTC, pomo-mondreganto commented on cmd/client/cmd/root.go
> +	rootCmd.PersistentFlags().StringP("config", "c", "config.yml", "config file")
В контейнере конфиг можно подсунуть туда, куда надо (так и делается сейчас в клиентском окружении)

2021-06-02 22:34 UTC, pomo-mondreganto commented on client_env/entrypoint.sh
> +echo "${ID}" >/etc/machine-id
Эта штука:

```
dbus-uuidgen --ensure="${ID_FILE}"
```

Проверяет, есть ли файлик, и генерирует новый id, если его нет

2021-06-02 22:34 UTC, pomo-mondreganto commented on LICENSE
> +Copyright (c) 2021 Roman Nikitin
Это всё Github))

2021-06-02 22:35 UTC, pomo-mondreganto commented on lib/proto/neo.proto
> +message Empty {}
Это как раз потому что результаты возвращать нетривиально. Кажется, можно это сделать, но предлагаю уже в рамках 3 версии этим заняться. Курсач же как-то надо закрывать)

2021-06-02 22:36 UTC, pomo-mondreganto commented on cmd/client/cli/run.go
> +const JobsPerCPU = 10
Подобрано. Возможно, имеет смысл сделать 5. В целом 10 работало неплохо на последнем соревновании. Не очень понятно, как нормально её определять, но и запускать 1 джоб на ядро -- плохая идея, в эксплоитах всегда много io

2021-06-02 22:37 UTC, pomo-mondreganto commented on cmd/client/cli/broadcast.go
> +	}
В 3 версию можно. Заведи issue, если согласен. Аналогично про возврат результатов broadcast и singlerun

2021-06-02 22:38 UTC, pomo-mondreganto commented on cmd/client/cli/add.go
> +		// PYTHONUNBUFFERED=1 is set for python scripts, so no need to flush the buffer
Там проверка для всего, что не содержит питоновский шебанг. Возможно, проверку стоит сделать менее жесткую по полному совпадению

2021-06-02 22:38 UTC, pomo-mondreganto commented on cmd/client/cli/utils.go
> +var binaryExtensions = []string{
1. А зачем?

2021-06-02 22:38 UTC, pomo-mondreganto commented on cmd/client/cli/utils.go
> +var binaryExtensions = []string{
2. Да, нормальная идея. Проверять первые 4 байта и смотреть, ELF или нет

2021-06-02 22:39 UTC, pomo-mondreganto commented on cmd/client/cmd/single.go
> +	Short: "Run an exploit once on all teams immediately",
"Один раз прямо сейчас запустить эксплоит", если вдруг сервис починили/подняли, например

2021-06-02 22:40 UTC, pomo-mondreganto commented on cmd/client/cmd/single.go
> +	Short: "Run an exploit once on all teams immediately",
Или для тестирования эксплоита потенциально. Добавляешь выключенный эксплоит, одноразовыми запусками отлаживаешь

2021-06-02 22:41 UTC, pomo-mondreganto commented on configs/server/config.yml
> +ping_every: "5s"
Работало, на самом деле, отлично на последнем стф. Много ставить тоже не стоит (это же и период обновления эксплоитов), секунд 15 звучит нормально. Всё равно эта настройка в конфиге, можно менять по желанию

2021-06-02 22:42 UTC, pomo-mondreganto commented on internal/queue/endless.go
> +var _ Factory = NewEndlessQueue
Да. А где они должны быть?

2021-06-02 22:43 UTC, pomo-mondreganto commented on internal/queue/endless.go
> +		err := safeReadOutput(r, dataCb)
Да, звучит неплохо. Только, возможно, не очень хорошо будет работать на больших бинарных блобах (там может закончиться буфер и произойти рандомный сплит посередине флага, либо сильный импакт на оперативку, если буфер бесконечный)

2021-06-02 22:44 UTC, pomo-mondreganto commented on internal/queue/endless_test.go
> +			t.Errorf("simpleQueue.Add(): got error = %v, want = %v", err, tc.wantErr)
Справедливо.

2021-06-02 22:44 UTC, pomo-mondreganto commented on internal/queue/endless_test.go
> +			t.Errorf("simpleQueue.Add(): got unexpected data = %v, want = %v", tk, tc.t)
Справедливо.

2021-06-02 22:45 UTC, pomo-mondreganto commented on internal/exploit/runner.go
> +	state, err := r.pingHeartbeat(ctx)
Справедливо.

2021-06-02 22:47 UTC, pomo-mondreganto commented on internal/client/client.go
> +			if errors.Is(stream.Context().Err(), context.Canceled) {
Да, хорошая мысль. Хотел уйти от глобальной копипасты (#хочудженерики) и не заметил, что можно хотя бы в ошибках пофиксить

2021-06-02 22:48 UTC, pomo-mondreganto commented on internal/exploit/cache.go
> +			continue
Расширяемость (если дальше что-то дописывать, это не надо будет менять

2021-06-02 22:50 UTC, pomo-mondreganto commented on internal/exploit/cache.go
> +	states map[string]*State
Вроде ради 74 строки (обновление LastRun в мапе inplace). Если я ошибаюсь и можно делать без указателя такое, скажи

2021-06-02 22:50 UTC, pomo-mondreganto commented on internal/exploit/submit_loop.go
> +	// TODO: Change this to config parameter.
Да, надо в серверный конфиг вынести

2021-06-02 22:51 UTC, pomo-mondreganto commented on internal/exploit/submit_loop.go
> +	defer close(l.finished)
Stop как раз ждет закрытия этого канала, закрывая done

2021-06-02 22:52 UTC, pomo-mondreganto commented on internal/queue/endless.go
> +		<-errC
Дождаться завершения горутины запуска эксплоита

2021-06-02 22:54 UTC, pomo-mondreganto commented on internal/queue/endless.go
> +	defer cancel()
Эта функция блокируется, пока не закончится выполнение эксплоита, либо её не прервут по внешнему контексту. cancel вызывается у внутреннего контекста, который, и правда, контролирует запуск эксплоита

2021-06-02 22:54 UTC, pomo-mondreganto commented on internal/queue/endless_test.go
> +//func Test_endlessQueue_runExploit(t *testing.T) {
Хороший вопрос. Не дописан, кажется

2021-06-02 22:55 UTC, pomo-mondreganto commented on internal/queue/simple.go
> +		<-errC
Дождаться конца горутины чтения

2021-06-02 22:58 UTC, pomo-mondreganto commented on lib/proto/neo.proto
> +message Empty {}
Плюс Empty неплохо подходит для глобальных подписок на события (`BroadcastRequests` и `SingleRunRequests`)

2021-06-02 23:01 UTC, pomo-mondreganto commented on lib/proto/neo.proto
> +  bool disabled = 4;
Отличать заполненный булин от незаполненного проблематично. С endless в конфиге -- согласен. disabled -- часть состояния, кажется, логично.

2021-06-23 18:25 UTC, pomo-mondreganto commented on internal/exploit/runner.go
> +			r.submitEndlessExploits(endlessLoop)
Сейчас это слишком сложно. Мне кажется, в этом особого смысла нет. Там на каждый эксплоит создается по <количество команд> тасков, то есть их надо все отменить и заново отправить

2021-06-23 18:28 UTC, pomo-mondreganto commented on internal/exploit/runner.go
>  func (r *Runner) updateExploits(ctx context.Context, exs []*neopb.ExploitState) {
Так она не перезапускает, а говорит ивентлупу перезапустить

2021-06-23 18:59 UTC, pomo-mondreganto commented on internal/exploit/cache.go
> +func (c *Cache) Update(exs []*State) {
Потому что внутри всё равно лежат указатели

2021-06-23 19:04 UTC, pomo-mondreganto commented on internal/exploit/runner.go
> +	simpleLoop := newSubmitLoop(r.maxJobs, r.cfg, queue.NewSimpleQueue)
Это не очень приятно, потому что тогда сложно будет перезапускать очереди (endless и обычную) по отдельности (сейчас перезапускается сразу submit loop). Поэтому же не очень удобно перезапускать точечно бесконечные эксплоиты.

2021-06-23 19:04 UTC, pomo-mondreganto commented on internal/queue/utils.go
> +func safeReadOutput(r io.Reader, cb readCallback) error {
done

2021-06-23 19:05 UTC, pomo-mondreganto commented on internal/queue/endless_test.go
> +//func Test_endlessQueue_runExploit(t *testing.T) {
И не будет дописан...

2021-06-23 19:05 UTC, pomo-mondreganto commented on internal/exploit/runner.go
> +		case <-r.endlessRestarts:
Ничего не придумалось

2021-08-19 14:34 UTC, jnovikov reviewed
LGTM, надо пофиксить баг с [neo] [neo] и потестить

2021-08-19 14:34 UTC, jnovikov commented on internal/exploit/submit_loop.go
> +			logrus.Errorf("Failed to submit flags to farm: %v", err)
Вот здесь по факту и появляется bug с [neo] [neo]

Если произошла ошибка отправки, то функция submitResults уже добавит всем эксплойтам префикс [neo] и так как слайс передан по ссылке, то в след попытку flush будет добавлен второй раз [neo].

Фикс кажется простой - передавать копию в функцию.

2021-08-19 14:37 UTC, jnovikov reviewed
Еще багос

2021-08-19 14:37 UTC, jnovikov commented on cmd/server/main.go
> +	configFile = pflag.StringP("config", "c", "client_config.yml", "yaml config file")
server_config.yml

2021-08-19 17:13 UTC, jnovikov approved these changes
LGTM

2021-08-19 17:52 UTC, merged